# Dockerfile.fastapi
FROM python:3.12-slim

WORKDIR /app

COPY interpreter-py/*.* ./
RUN pip install --no-cache-dir -r requirements.txt

# Run tests and start the application
CMD pytest -v tests.py && uvicorn main:app --host 0.0.0.0 --port 8000

# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]