# Dockerfile.fastapi
FROM python:3.9

WORKDIR /app

COPY codebase-indexer/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY codebase-indexer/*.* .

EXPOSE 7779
EXPOSE 1234

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "7779"]