# Dockerfile.fastapi
FROM python:3.12-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    git vim\
    && rm -rf /var/lib/apt/lists/*

# Copy project
COPY codebase-indexer/*.* ./
RUN pip install --no-cache-dir -r requirements.txt

# Run the application
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "7779"]