FROM python:3.9

WORKDIR /app

COPY codebase-indexer/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY codebase-indexer/*.py .

EXPOSE 7779

CMD ["sh", "-c", "uvicorn app:app --host 0.0.0.0 --port 7779"]